apiVersion: v1
kind: Service
metadata:
  name: {{ include "pravah.fullname" . }}-api
  labels:
    {{- include "pravah.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort | default 8000 }}
      protocol: TCP
      name: http
  selector:
    {{- include "pravah.apiSelectorLabels" . | nindent 4 }}
