apiVersion: v1
kind: Service
metadata:
  name: {{ include "pravah.fullname" . }}-web
  labels:
    {{- include "pravah.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.web.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort | default 3000 }}
      protocol: TCP
      name: http
  selector:
    {{- include "pravah.webSelectorLabels" . | nindent 4 }}
