"""workflow_versioning_secret_refs_templates

Revision ID: 807b210b9de7
Revises: c61b97841082
Create Date: 2026-09-02 14:08:51.369754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807b210b9de7'
down_revision: Union[str, None] = 'c61b97841082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_templates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('graph_data', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin_template', sa.Boolean(), nullable=False),
    sa.Column('plan_requirements', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('organisation_id', sa.String(length=36), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_templates_id'), 'workflow_templates', ['id'], unique=False)
    op.create_table('workflow_run_locks',
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_released', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('idempotency_key', name='uq_workflow_run_lock_key')
    )
    op.create_index(op.f('ix_workflow_run_locks_id'), 'workflow_run_locks', ['id'], unique=False)
    op.create_table('workflow_secret_references',
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('ref_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('encrypted_value', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'ref_name', name='uq_workflow_secret_ref')
    )
    op.create_index(op.f('ix_workflow_secret_references_id'), 'workflow_secret_references', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_secret_references_organisation_id'), 'workflow_secret_references', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_workflow_secret_references_workflow_id'), 'workflow_secret_references', ['workflow_id'], unique=False)
    op.create_table('workflow_variables',
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('value_type', sa.String(length=50), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_secret_ref', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'key', name='uq_workflow_variable_key')
    )
    op.create_index(op.f('ix_workflow_variables_id'), 'workflow_variables', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_variables_workflow_id'), 'workflow_variables', ['workflow_id'], unique=False)
    op.create_table('workflow_versions',
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('published_by_id', sa.String(length=36), nullable=True),
    sa.Column('graph_snapshot', sa.JSON(), nullable=False),
    sa.Column('variables_snapshot', sa.JSON(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'version_number', name='uq_workflow_version')
    )
    op.create_index(op.f('ix_workflow_versions_id'), 'workflow_versions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_versions_workflow_id'), 'workflow_versions', ['workflow_id'], unique=False)
    op.add_column('workflow_edges', sa.Column('edge_type', sa.String(length=50), nullable=True))
    op.add_column('workflow_executions', sa.Column('workflow_version', sa.Integer(), nullable=True))
    op.add_column('workflow_executions', sa.Column('trigger_payload', sa.JSON(), nullable=True))
    op.add_column('workflow_executions', sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflow_executions', sa.Column('retry_count', sa.Integer(), nullable=True))
    # SQLite doesn't support ALTER COLUMN — use batch mode
    with op.batch_alter_table('workflow_executions') as batch_op:
        batch_op.alter_column('started_at', existing_type=sa.DATETIME(), nullable=True)
    op.add_column('workflow_node_executions', sa.Column('retry_count', sa.Integer(), nullable=True))
    with op.batch_alter_table('workflow_node_executions') as batch_op:
        batch_op.alter_column('node_name', existing_type=sa.VARCHAR(length=100),
                              type_=sa.String(length=200), existing_nullable=False)
        batch_op.alter_column('started_at', existing_type=sa.DATETIME(), nullable=True)
    op.add_column('workflow_nodes', sa.Column('label', sa.String(length=200), nullable=True))
    op.add_column('workflow_nodes', sa.Column('color', sa.String(length=20), nullable=True))
    op.add_column('workflow_nodes', sa.Column('notes', sa.Text(), nullable=True))
    with op.batch_alter_table('workflow_nodes') as batch_op:
        batch_op.alter_column('name', existing_type=sa.VARCHAR(length=100),
                              type_=sa.String(length=200), existing_nullable=False)
        batch_op.alter_column('position_x', existing_type=sa.INTEGER(),
                              type_=sa.Float(), existing_nullable=False)
        batch_op.alter_column('position_y', existing_type=sa.INTEGER(),
                              type_=sa.Float(), existing_nullable=False)
    op.add_column('workflows', sa.Column('published_version', sa.Integer(), nullable=True))
    op.add_column('workflows', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('workflows', sa.Column('icon', sa.String(length=100), nullable=True))
    op.add_column('workflows', sa.Column('color', sa.String(length=20), nullable=True))
    op.add_column('workflows', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('workflows', sa.Column('requires_approval', sa.Boolean(), nullable=True))
    op.add_column('workflows', sa.Column('approval_mode', sa.String(length=50), nullable=True))
    op.add_column('workflows', sa.Column('last_execution_status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_workflows_status'), 'workflows', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_status'), table_name='workflows')
    op.drop_column('workflows', 'last_execution_status')
    op.drop_column('workflows', 'approval_mode')
    op.drop_column('workflows', 'requires_approval')
    op.drop_column('workflows', 'notes')
    op.drop_column('workflows', 'color')
    op.drop_column('workflows', 'icon')
    op.drop_column('workflows', 'tags')
    op.drop_column('workflows', 'published_version')
    op.alter_column('workflow_nodes', 'position_y',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('workflow_nodes', 'position_x',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('workflow_nodes', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('workflow_nodes', 'notes')
    op.drop_column('workflow_nodes', 'color')
    op.drop_column('workflow_nodes', 'label')
    op.alter_column('workflow_node_executions', 'started_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('workflow_node_executions', 'node_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('workflow_node_executions', 'retry_count')
    op.alter_column('workflow_executions', 'started_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_column('workflow_executions', 'retry_count')
    op.drop_column('workflow_executions', 'queued_at')
    op.drop_column('workflow_executions', 'trigger_payload')
    op.drop_column('workflow_executions', 'workflow_version')
    op.drop_column('workflow_edges', 'edge_type')
    op.drop_index(op.f('ix_workflow_versions_workflow_id'), table_name='workflow_versions')
    op.drop_index(op.f('ix_workflow_versions_id'), table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_index(op.f('ix_workflow_variables_workflow_id'), table_name='workflow_variables')
    op.drop_index(op.f('ix_workflow_variables_id'), table_name='workflow_variables')
    op.drop_table('workflow_variables')
    op.drop_index(op.f('ix_workflow_secret_references_workflow_id'), table_name='workflow_secret_references')
    op.drop_index(op.f('ix_workflow_secret_references_organisation_id'), table_name='workflow_secret_references')
    op.drop_index(op.f('ix_workflow_secret_references_id'), table_name='workflow_secret_references')
    op.drop_table('workflow_secret_references')
    op.drop_index(op.f('ix_workflow_run_locks_id'), table_name='workflow_run_locks')
    op.drop_table('workflow_run_locks')
    op.drop_index(op.f('ix_workflow_templates_id'), table_name='workflow_templates')
    op.drop_table('workflow_templates')
    # ### end Alembic commands ###
